// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user_mgr.proto

package server

import (
	"context"

	"user_mgr/internal/logic"
	"user_mgr/internal/svc"
	"user_mgr/user_mgr_pb"
)

type UserMgrServer struct {
	svcCtx *svc.ServiceContext
	user_mgr_pb.UnimplementedUserMgrServer
}

func NewUserMgrServer(svcCtx *svc.ServiceContext) *UserMgrServer {
	return &UserMgrServer{
		svcCtx: svcCtx,
	}
}

func (s *UserMgrServer) RegUser(ctx context.Context, in *user_mgr_pb.RegUserReq) (*user_mgr_pb.RegUserRsp, error) {
	l := logic.NewRegUserLogic(ctx, s.svcCtx)
	return l.RegUser(in)
}

func (s *UserMgrServer) UpdateUserInfo(ctx context.Context, in *user_mgr_pb.UpdateUserInfoReq) (*user_mgr_pb.UpdateUserInfoRsp, error) {
	l := logic.NewUpdateUserInfoLogic(ctx, s.svcCtx)
	return l.UpdateUserInfo(in)
}

func (s *UserMgrServer) GetUserInfo(ctx context.Context, in *user_mgr_pb.GetUserInfoReq) (*user_mgr_pb.GetUserInfoRsp, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}
