// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user_mgr.proto

package server

import (
	"context"

	"github.com/starslipay/user_mgr/internal/logic"
	"github.com/starslipay/user_mgr/internal/svc"
	"github.com/starslipay/user_mgr/user_mgr_pb"
)

type UserMgrServer struct {
	svcCtx *svc.ServiceContext
	user_mgr_pb.UnimplementedUserMgrServer
}

func NewUserMgrServer(svcCtx *svc.ServiceContext) *UserMgrServer {
	return &UserMgrServer{
		svcCtx: svcCtx,
	}
}

func (s *UserMgrServer) RegUser(ctx context.Context, in *user_mgr_pb.RegUserReq) (*user_mgr_pb.RegUserRsp, error) {
	l := logic.NewRegUserLogic(ctx, s.svcCtx)
	return l.RegUser(in)
}

func (s *UserMgrServer) UpdateUserInfo(ctx context.Context, in *user_mgr_pb.UpdateUserInfoReq) (*user_mgr_pb.UpdateUserInfoRsp, error) {
	l := logic.NewUpdateUserInfoLogic(ctx, s.svcCtx)
	return l.UpdateUserInfo(in)
}

func (s *UserMgrServer) GetRelation(ctx context.Context, in *user_mgr_pb.GetRelationReq) (*user_mgr_pb.GetRelationRsp, error) {
	l := logic.NewGetRelationLogic(ctx, s.svcCtx)
	return l.GetRelation(in)
}

func (s *UserMgrServer) GetUserInfo(ctx context.Context, in *user_mgr_pb.GetUserInfoReq) (*user_mgr_pb.GetUserInfoRsp, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}

func (s *UserMgrServer) CheckPassword(ctx context.Context, in *user_mgr_pb.CheckPasswordReq) (*user_mgr_pb.CheckPasswordRsp, error) {
	l := logic.NewCheckPasswordLogic(ctx, s.svcCtx)
	return l.CheckPassword(in)
}

func (s *UserMgrServer) GetUserToken(ctx context.Context, in *user_mgr_pb.GetUserTokenReq) (*user_mgr_pb.GetUserTokenRsp, error) {
	l := logic.NewGetUserTokenLogic(ctx, s.svcCtx)
	return l.GetUserToken(in)
}

func (s *UserMgrServer) CheckUserToken(ctx context.Context, in *user_mgr_pb.CheckUserTokenReq) (*user_mgr_pb.CheckUserTokenRsp, error) {
	l := logic.NewCheckUserTokenLogic(ctx, s.svcCtx)
	return l.CheckUserToken(in)
}
