// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: user_mgr.proto

package user_mgr_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 注册用户Req
type RegUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Gender        int32                  `protobuf:"varint,5,opt,name=gender,proto3" json:"gender,omitempty"`
	Age           int32                  `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	Address       string                 `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	Phone         string                 `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,8,opt,name=email,proto3" json:"email,omitempty"`
	IdType        int32                  `protobuf:"varint,9,opt,name=id_type,json=idType,proto3" json:"id_type,omitempty"`
	IdCard        string                 `protobuf:"bytes,10,opt,name=id_card,json=idCard,proto3" json:"id_card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegUserReq) Reset() {
	*x = RegUserReq{}
	mi := &file_user_mgr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegUserReq) ProtoMessage() {}

func (x *RegUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_mgr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegUserReq.ProtoReflect.Descriptor instead.
func (*RegUserReq) Descriptor() ([]byte, []int) {
	return file_user_mgr_proto_rawDescGZIP(), []int{0}
}

func (x *RegUserReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegUserReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegUserReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegUserReq) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *RegUserReq) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *RegUserReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegUserReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *RegUserReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegUserReq) GetIdType() int32 {
	if x != nil {
		return x.IdType
	}
	return 0
}

func (x *RegUserReq) GetIdCard() string {
	if x != nil {
		return x.IdCard
	}
	return ""
}

type GetRelationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRelationReq) Reset() {
	*x = GetRelationReq{}
	mi := &file_user_mgr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRelationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRelationReq) ProtoMessage() {}

func (x *GetRelationReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_mgr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRelationReq.ProtoReflect.Descriptor instead.
func (*GetRelationReq) Descriptor() ([]byte, []int) {
	return file_user_mgr_proto_rawDescGZIP(), []int{1}
}

func (x *GetRelationReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetRelationRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Uid           int64                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRelationRsp) Reset() {
	*x = GetRelationRsp{}
	mi := &file_user_mgr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRelationRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRelationRsp) ProtoMessage() {}

func (x *GetRelationRsp) ProtoReflect() protoreflect.Message {
	mi := &file_user_mgr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRelationRsp.ProtoReflect.Descriptor instead.
func (*GetRelationRsp) Descriptor() ([]byte, []int) {
	return file_user_mgr_proto_rawDescGZIP(), []int{2}
}

func (x *GetRelationRsp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetRelationRsp) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

// 注册用户Rsp
type RegUserRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegUserRsp) Reset() {
	*x = RegUserRsp{}
	mi := &file_user_mgr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegUserRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegUserRsp) ProtoMessage() {}

func (x *RegUserRsp) ProtoReflect() protoreflect.Message {
	mi := &file_user_mgr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegUserRsp.ProtoReflect.Descriptor instead.
func (*RegUserRsp) Descriptor() ([]byte, []int) {
	return file_user_mgr_proto_rawDescGZIP(), []int{3}
}

func (x *RegUserRsp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoReq) Reset() {
	*x = GetUserInfoReq{}
	mi := &file_user_mgr_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoReq) ProtoMessage() {}

func (x *GetUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_mgr_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoReq.ProtoReflect.Descriptor instead.
func (*GetUserInfoReq) Descriptor() ([]byte, []int) {
	return file_user_mgr_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserInfoReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserInfoRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Gender        int32                  `protobuf:"varint,3,opt,name=gender,proto3" json:"gender,omitempty"`
	Age           int32                  `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	Address       string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Phone         string                 `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	IdType        int32                  `protobuf:"varint,8,opt,name=id_type,json=idType,proto3" json:"id_type,omitempty"`
	IdCard        string                 `protobuf:"bytes,9,opt,name=id_card,json=idCard,proto3" json:"id_card,omitempty"`
	Uid           int64                  `protobuf:"varint,10,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoRsp) Reset() {
	*x = GetUserInfoRsp{}
	mi := &file_user_mgr_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRsp) ProtoMessage() {}

func (x *GetUserInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_user_mgr_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRsp.ProtoReflect.Descriptor instead.
func (*GetUserInfoRsp) Descriptor() ([]byte, []int) {
	return file_user_mgr_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserInfoRsp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserInfoRsp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetUserInfoRsp) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *GetUserInfoRsp) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *GetUserInfoRsp) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetUserInfoRsp) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *GetUserInfoRsp) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetUserInfoRsp) GetIdType() int32 {
	if x != nil {
		return x.IdType
	}
	return 0
}

func (x *GetUserInfoRsp) GetIdCard() string {
	if x != nil {
		return x.IdCard
	}
	return ""
}

func (x *GetUserInfoRsp) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

// 更新用户信息
type UpdateUserInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Gender        int32                  `protobuf:"varint,3,opt,name=gender,proto3" json:"gender,omitempty"`
	Age           int32                  `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	Address       string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Phone         string                 `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	IdType        int32                  `protobuf:"varint,8,opt,name=id_type,json=idType,proto3" json:"id_type,omitempty"`
	IdCard        string                 `protobuf:"bytes,9,opt,name=id_card,json=idCard,proto3" json:"id_card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserInfoReq) Reset() {
	*x = UpdateUserInfoReq{}
	mi := &file_user_mgr_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserInfoReq) ProtoMessage() {}

func (x *UpdateUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_mgr_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserInfoReq.ProtoReflect.Descriptor instead.
func (*UpdateUserInfoReq) Descriptor() ([]byte, []int) {
	return file_user_mgr_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateUserInfoReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserInfoReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateUserInfoReq) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *UpdateUserInfoReq) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *UpdateUserInfoReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UpdateUserInfoReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateUserInfoReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserInfoReq) GetIdType() int32 {
	if x != nil {
		return x.IdType
	}
	return 0
}

func (x *UpdateUserInfoReq) GetIdCard() string {
	if x != nil {
		return x.IdCard
	}
	return ""
}

type UpdateUserInfoRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserInfoRsp) Reset() {
	*x = UpdateUserInfoRsp{}
	mi := &file_user_mgr_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserInfoRsp) ProtoMessage() {}

func (x *UpdateUserInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_user_mgr_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserInfoRsp.ProtoReflect.Descriptor instead.
func (*UpdateUserInfoRsp) Descriptor() ([]byte, []int) {
	return file_user_mgr_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateUserInfoRsp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CheckPasswordReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPasswordReq) Reset() {
	*x = CheckPasswordReq{}
	mi := &file_user_mgr_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPasswordReq) ProtoMessage() {}

func (x *CheckPasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_mgr_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPasswordReq.ProtoReflect.Descriptor instead.
func (*CheckPasswordReq) Descriptor() ([]byte, []int) {
	return file_user_mgr_proto_rawDescGZIP(), []int{8}
}

func (x *CheckPasswordReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckPasswordReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CheckPasswordRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPasswordRsp) Reset() {
	*x = CheckPasswordRsp{}
	mi := &file_user_mgr_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPasswordRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPasswordRsp) ProtoMessage() {}

func (x *CheckPasswordRsp) ProtoReflect() protoreflect.Message {
	mi := &file_user_mgr_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPasswordRsp.ProtoReflect.Descriptor instead.
func (*CheckPasswordRsp) Descriptor() ([]byte, []int) {
	return file_user_mgr_proto_rawDescGZIP(), []int{9}
}

type GetUserTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	BusinessInfo  string                 `protobuf:"bytes,3,opt,name=business_info,json=businessInfo,proto3" json:"business_info,omitempty"` // 业务信息, 会参生成token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserTokenReq) Reset() {
	*x = GetUserTokenReq{}
	mi := &file_user_mgr_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserTokenReq) ProtoMessage() {}

func (x *GetUserTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_mgr_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserTokenReq.ProtoReflect.Descriptor instead.
func (*GetUserTokenReq) Descriptor() ([]byte, []int) {
	return file_user_mgr_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserTokenReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserTokenReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *GetUserTokenReq) GetBusinessInfo() string {
	if x != nil {
		return x.BusinessInfo
	}
	return ""
}

type GetUserTokenRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserToken     string                 `protobuf:"bytes,1,opt,name=user_token,json=userToken,proto3" json:"user_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserTokenRsp) Reset() {
	*x = GetUserTokenRsp{}
	mi := &file_user_mgr_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserTokenRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserTokenRsp) ProtoMessage() {}

func (x *GetUserTokenRsp) ProtoReflect() protoreflect.Message {
	mi := &file_user_mgr_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserTokenRsp.ProtoReflect.Descriptor instead.
func (*GetUserTokenRsp) Descriptor() ([]byte, []int) {
	return file_user_mgr_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserTokenRsp) GetUserToken() string {
	if x != nil {
		return x.UserToken
	}
	return ""
}

var File_user_mgr_proto protoreflect.FileDescriptor

const file_user_mgr_proto_rawDesc = "" +
	"\n" +
	"\x0euser_mgr.proto\x12\buser_mgr\"\xf7\x01\n" +
	"\n" +
	"RegUserReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\x05R\x06gender\x12\x10\n" +
	"\x03age\x18\x04 \x01(\x05R\x03age\x12\x18\n" +
	"\aaddress\x18\x06 \x01(\tR\aaddress\x12\x14\n" +
	"\x05phone\x18\a \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\b \x01(\tR\x05email\x12\x17\n" +
	"\aid_type\x18\t \x01(\x05R\x06idType\x12\x17\n" +
	"\aid_card\x18\n" +
	" \x01(\tR\x06idCard\")\n" +
	"\x0eGetRelationReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\";\n" +
	"\x0eGetRelationRsp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x03R\x03uid\"%\n" +
	"\n" +
	"RegUserRsp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\")\n" +
	"\x0eGetUserInfoReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xf1\x01\n" +
	"\x0eGetUserInfoRsp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06gender\x18\x03 \x01(\x05R\x06gender\x12\x10\n" +
	"\x03age\x18\x04 \x01(\x05R\x03age\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\a \x01(\tR\x05email\x12\x17\n" +
	"\aid_type\x18\b \x01(\x05R\x06idType\x12\x17\n" +
	"\aid_card\x18\t \x01(\tR\x06idCard\x12\x10\n" +
	"\x03uid\x18\n" +
	" \x01(\x03R\x03uid\"\xe2\x01\n" +
	"\x11UpdateUserInfoReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06gender\x18\x03 \x01(\x05R\x06gender\x12\x10\n" +
	"\x03age\x18\x04 \x01(\x05R\x03age\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\a \x01(\tR\x05email\x12\x17\n" +
	"\aid_type\x18\b \x01(\x05R\x06idType\x12\x17\n" +
	"\aid_card\x18\t \x01(\tR\x06idCard\",\n" +
	"\x11UpdateUserInfoRsp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"G\n" +
	"\x10CheckPasswordReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x12\n" +
	"\x10CheckPasswordRsp\"k\n" +
	"\x0fGetUserTokenReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12#\n" +
	"\rbusiness_info\x18\x03 \x01(\tR\fbusinessInfo\"0\n" +
	"\x0fGetUserTokenRsp\x12\x1d\n" +
	"\n" +
	"user_token\x18\x01 \x01(\tR\tuserToken2\xa1\x03\n" +
	"\aUserMgr\x125\n" +
	"\aRegUser\x12\x14.user_mgr.RegUserReq\x1a\x14.user_mgr.RegUserRsp\x12J\n" +
	"\x0eUpdateUserInfo\x12\x1b.user_mgr.UpdateUserInfoReq\x1a\x1b.user_mgr.UpdateUserInfoRsp\x12A\n" +
	"\vGetRelation\x12\x18.user_mgr.GetRelationReq\x1a\x18.user_mgr.GetRelationRsp\x12A\n" +
	"\vGetUserInfo\x12\x18.user_mgr.GetUserInfoReq\x1a\x18.user_mgr.GetUserInfoRsp\x12G\n" +
	"\rCheckPassword\x12\x1a.user_mgr.CheckPasswordReq\x1a\x1a.user_mgr.CheckPasswordRsp\x12D\n" +
	"\fGetUserToken\x12\x19.user_mgr.GetUserTokenReq\x1a\x19.user_mgr.GetUserTokenRspB\x0fZ\r./user_mgr_pbb\x06proto3"

var (
	file_user_mgr_proto_rawDescOnce sync.Once
	file_user_mgr_proto_rawDescData []byte
)

func file_user_mgr_proto_rawDescGZIP() []byte {
	file_user_mgr_proto_rawDescOnce.Do(func() {
		file_user_mgr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_mgr_proto_rawDesc), len(file_user_mgr_proto_rawDesc)))
	})
	return file_user_mgr_proto_rawDescData
}

var file_user_mgr_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_user_mgr_proto_goTypes = []any{
	(*RegUserReq)(nil),        // 0: user_mgr.RegUserReq
	(*GetRelationReq)(nil),    // 1: user_mgr.GetRelationReq
	(*GetRelationRsp)(nil),    // 2: user_mgr.GetRelationRsp
	(*RegUserRsp)(nil),        // 3: user_mgr.RegUserRsp
	(*GetUserInfoReq)(nil),    // 4: user_mgr.GetUserInfoReq
	(*GetUserInfoRsp)(nil),    // 5: user_mgr.GetUserInfoRsp
	(*UpdateUserInfoReq)(nil), // 6: user_mgr.UpdateUserInfoReq
	(*UpdateUserInfoRsp)(nil), // 7: user_mgr.UpdateUserInfoRsp
	(*CheckPasswordReq)(nil),  // 8: user_mgr.CheckPasswordReq
	(*CheckPasswordRsp)(nil),  // 9: user_mgr.CheckPasswordRsp
	(*GetUserTokenReq)(nil),   // 10: user_mgr.GetUserTokenReq
	(*GetUserTokenRsp)(nil),   // 11: user_mgr.GetUserTokenRsp
}
var file_user_mgr_proto_depIdxs = []int32{
	0,  // 0: user_mgr.UserMgr.RegUser:input_type -> user_mgr.RegUserReq
	6,  // 1: user_mgr.UserMgr.UpdateUserInfo:input_type -> user_mgr.UpdateUserInfoReq
	1,  // 2: user_mgr.UserMgr.GetRelation:input_type -> user_mgr.GetRelationReq
	4,  // 3: user_mgr.UserMgr.GetUserInfo:input_type -> user_mgr.GetUserInfoReq
	8,  // 4: user_mgr.UserMgr.CheckPassword:input_type -> user_mgr.CheckPasswordReq
	10, // 5: user_mgr.UserMgr.GetUserToken:input_type -> user_mgr.GetUserTokenReq
	3,  // 6: user_mgr.UserMgr.RegUser:output_type -> user_mgr.RegUserRsp
	7,  // 7: user_mgr.UserMgr.UpdateUserInfo:output_type -> user_mgr.UpdateUserInfoRsp
	2,  // 8: user_mgr.UserMgr.GetRelation:output_type -> user_mgr.GetRelationRsp
	5,  // 9: user_mgr.UserMgr.GetUserInfo:output_type -> user_mgr.GetUserInfoRsp
	9,  // 10: user_mgr.UserMgr.CheckPassword:output_type -> user_mgr.CheckPasswordRsp
	11, // 11: user_mgr.UserMgr.GetUserToken:output_type -> user_mgr.GetUserTokenRsp
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_user_mgr_proto_init() }
func file_user_mgr_proto_init() {
	if File_user_mgr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_mgr_proto_rawDesc), len(file_user_mgr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_mgr_proto_goTypes,
		DependencyIndexes: file_user_mgr_proto_depIdxs,
		MessageInfos:      file_user_mgr_proto_msgTypes,
	}.Build()
	File_user_mgr_proto = out.File
	file_user_mgr_proto_goTypes = nil
	file_user_mgr_proto_depIdxs = nil
}
