// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: user_mgr.proto

package user_mgr_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 注册用户Req
type RegUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Gender        int32                  `protobuf:"varint,5,opt,name=gender,proto3" json:"gender,omitempty"`
	Age           int32                  `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	Address       string                 `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	Phone         string                 `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,8,opt,name=email,proto3" json:"email,omitempty"`
	IdType        int32                  `protobuf:"varint,9,opt,name=id_type,json=idType,proto3" json:"id_type,omitempty"`
	IdCard        string                 `protobuf:"bytes,10,opt,name=id_card,json=idCard,proto3" json:"id_card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegUserReq) Reset() {
	*x = RegUserReq{}
	mi := &file_user_mgr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegUserReq) ProtoMessage() {}

func (x *RegUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_mgr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegUserReq.ProtoReflect.Descriptor instead.
func (*RegUserReq) Descriptor() ([]byte, []int) {
	return file_user_mgr_proto_rawDescGZIP(), []int{0}
}

func (x *RegUserReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegUserReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegUserReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegUserReq) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *RegUserReq) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *RegUserReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegUserReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *RegUserReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegUserReq) GetIdType() int32 {
	if x != nil {
		return x.IdType
	}
	return 0
}

func (x *RegUserReq) GetIdCard() string {
	if x != nil {
		return x.IdCard
	}
	return ""
}

// 注册用户Rsp
type RegUserRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsRepeat      int32                  `protobuf:"varint,2,opt,name=is_repeat,json=isRepeat,proto3" json:"is_repeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegUserRsp) Reset() {
	*x = RegUserRsp{}
	mi := &file_user_mgr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegUserRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegUserRsp) ProtoMessage() {}

func (x *RegUserRsp) ProtoReflect() protoreflect.Message {
	mi := &file_user_mgr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegUserRsp.ProtoReflect.Descriptor instead.
func (*RegUserRsp) Descriptor() ([]byte, []int) {
	return file_user_mgr_proto_rawDescGZIP(), []int{1}
}

func (x *RegUserRsp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegUserRsp) GetIsRepeat() int32 {
	if x != nil {
		return x.IsRepeat
	}
	return 0
}

type GetUserInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoReq) Reset() {
	*x = GetUserInfoReq{}
	mi := &file_user_mgr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoReq) ProtoMessage() {}

func (x *GetUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_mgr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoReq.ProtoReflect.Descriptor instead.
func (*GetUserInfoReq) Descriptor() ([]byte, []int) {
	return file_user_mgr_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserInfoReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserInfoRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Gender        int32                  `protobuf:"varint,3,opt,name=gender,proto3" json:"gender,omitempty"`
	Age           int32                  `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	Address       string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Phone         string                 `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	IdType        int32                  `protobuf:"varint,8,opt,name=id_type,json=idType,proto3" json:"id_type,omitempty"`
	IdCard        string                 `protobuf:"bytes,9,opt,name=id_card,json=idCard,proto3" json:"id_card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoRsp) Reset() {
	*x = GetUserInfoRsp{}
	mi := &file_user_mgr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRsp) ProtoMessage() {}

func (x *GetUserInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_user_mgr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRsp.ProtoReflect.Descriptor instead.
func (*GetUserInfoRsp) Descriptor() ([]byte, []int) {
	return file_user_mgr_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserInfoRsp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserInfoRsp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetUserInfoRsp) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *GetUserInfoRsp) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *GetUserInfoRsp) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetUserInfoRsp) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *GetUserInfoRsp) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetUserInfoRsp) GetIdType() int32 {
	if x != nil {
		return x.IdType
	}
	return 0
}

func (x *GetUserInfoRsp) GetIdCard() string {
	if x != nil {
		return x.IdCard
	}
	return ""
}

type GetUserBalanceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserBalanceReq) Reset() {
	*x = GetUserBalanceReq{}
	mi := &file_user_mgr_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserBalanceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBalanceReq) ProtoMessage() {}

func (x *GetUserBalanceReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_mgr_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBalanceReq.ProtoReflect.Descriptor instead.
func (*GetUserBalanceReq) Descriptor() ([]byte, []int) {
	return file_user_mgr_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserBalanceReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserBalanceRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Balance       int64                  `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserBalanceRsp) Reset() {
	*x = GetUserBalanceRsp{}
	mi := &file_user_mgr_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserBalanceRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBalanceRsp) ProtoMessage() {}

func (x *GetUserBalanceRsp) ProtoReflect() protoreflect.Message {
	mi := &file_user_mgr_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBalanceRsp.ProtoReflect.Descriptor instead.
func (*GetUserBalanceRsp) Descriptor() ([]byte, []int) {
	return file_user_mgr_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserBalanceRsp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserBalanceRsp) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

// 更新用户信息
type UpdateUserInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Gender        int32                  `protobuf:"varint,3,opt,name=gender,proto3" json:"gender,omitempty"`
	Age           int32                  `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	Address       string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Phone         string                 `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	IdType        int32                  `protobuf:"varint,8,opt,name=id_type,json=idType,proto3" json:"id_type,omitempty"`
	IdCard        string                 `protobuf:"bytes,9,opt,name=id_card,json=idCard,proto3" json:"id_card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserInfoReq) Reset() {
	*x = UpdateUserInfoReq{}
	mi := &file_user_mgr_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserInfoReq) ProtoMessage() {}

func (x *UpdateUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_mgr_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserInfoReq.ProtoReflect.Descriptor instead.
func (*UpdateUserInfoReq) Descriptor() ([]byte, []int) {
	return file_user_mgr_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateUserInfoReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserInfoReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateUserInfoReq) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *UpdateUserInfoReq) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *UpdateUserInfoReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UpdateUserInfoReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateUserInfoReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserInfoReq) GetIdType() int32 {
	if x != nil {
		return x.IdType
	}
	return 0
}

func (x *UpdateUserInfoReq) GetIdCard() string {
	if x != nil {
		return x.IdCard
	}
	return ""
}

type UpdateUserInfoRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserInfoRsp) Reset() {
	*x = UpdateUserInfoRsp{}
	mi := &file_user_mgr_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserInfoRsp) ProtoMessage() {}

func (x *UpdateUserInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_user_mgr_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserInfoRsp.ProtoReflect.Descriptor instead.
func (*UpdateUserInfoRsp) Descriptor() ([]byte, []int) {
	return file_user_mgr_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateUserInfoRsp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// 充值
type DepositReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	BankType      int64                  `protobuf:"varint,3,opt,name=bank_type,json=bankType,proto3" json:"bank_type,omitempty"`
	BindSerial    string                 `protobuf:"bytes,4,opt,name=bind_serial,json=bindSerial,proto3" json:"bind_serial,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositReq) Reset() {
	*x = DepositReq{}
	mi := &file_user_mgr_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositReq) ProtoMessage() {}

func (x *DepositReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_mgr_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositReq.ProtoReflect.Descriptor instead.
func (*DepositReq) Descriptor() ([]byte, []int) {
	return file_user_mgr_proto_rawDescGZIP(), []int{8}
}

func (x *DepositReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DepositReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DepositReq) GetBankType() int64 {
	if x != nil {
		return x.BankType
	}
	return 0
}

func (x *DepositReq) GetBindSerial() string {
	if x != nil {
		return x.BindSerial
	}
	return ""
}

func (x *DepositReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type DepositRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Balance       int64                  `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositRsp) Reset() {
	*x = DepositRsp{}
	mi := &file_user_mgr_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositRsp) ProtoMessage() {}

func (x *DepositRsp) ProtoReflect() protoreflect.Message {
	mi := &file_user_mgr_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositRsp.ProtoReflect.Descriptor instead.
func (*DepositRsp) Descriptor() ([]byte, []int) {
	return file_user_mgr_proto_rawDescGZIP(), []int{9}
}

func (x *DepositRsp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DepositRsp) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

// 提现
type WithdrawReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	BankType      int64                  `protobuf:"varint,3,opt,name=bank_type,json=bankType,proto3" json:"bank_type,omitempty"`
	BindSerial    string                 `protobuf:"bytes,4,opt,name=bind_serial,json=bindSerial,proto3" json:"bind_serial,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawReq) Reset() {
	*x = WithdrawReq{}
	mi := &file_user_mgr_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawReq) ProtoMessage() {}

func (x *WithdrawReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_mgr_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawReq.ProtoReflect.Descriptor instead.
func (*WithdrawReq) Descriptor() ([]byte, []int) {
	return file_user_mgr_proto_rawDescGZIP(), []int{10}
}

func (x *WithdrawReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *WithdrawReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *WithdrawReq) GetBankType() int64 {
	if x != nil {
		return x.BankType
	}
	return 0
}

func (x *WithdrawReq) GetBindSerial() string {
	if x != nil {
		return x.BindSerial
	}
	return ""
}

func (x *WithdrawReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type WithdrawRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Balance       int64                  `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawRsp) Reset() {
	*x = WithdrawRsp{}
	mi := &file_user_mgr_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawRsp) ProtoMessage() {}

func (x *WithdrawRsp) ProtoReflect() protoreflect.Message {
	mi := &file_user_mgr_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawRsp.ProtoReflect.Descriptor instead.
func (*WithdrawRsp) Descriptor() ([]byte, []int) {
	return file_user_mgr_proto_rawDescGZIP(), []int{11}
}

func (x *WithdrawRsp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *WithdrawRsp) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

// 获取用户流水
type GetUserFlowReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"` // 分页偏移量
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`   // 分页大小
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserFlowReq) Reset() {
	*x = GetUserFlowReq{}
	mi := &file_user_mgr_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserFlowReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserFlowReq) ProtoMessage() {}

func (x *GetUserFlowReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_mgr_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserFlowReq.ProtoReflect.Descriptor instead.
func (*GetUserFlowReq) Descriptor() ([]byte, []int) {
	return file_user_mgr_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserFlowReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserFlowReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetUserFlowReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetUserFlowRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Flow          []*GetUserFlowItemRsp  `protobuf:"bytes,2,rep,name=flow,proto3" json:"flow,omitempty"`
	Flag          int32                  `protobuf:"varint,3,opt,name=flag,proto3" json:"flag,omitempty"`     // 查询结束标记
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"` // 分页偏移量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserFlowRsp) Reset() {
	*x = GetUserFlowRsp{}
	mi := &file_user_mgr_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserFlowRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserFlowRsp) ProtoMessage() {}

func (x *GetUserFlowRsp) ProtoReflect() protoreflect.Message {
	mi := &file_user_mgr_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserFlowRsp.ProtoReflect.Descriptor instead.
func (*GetUserFlowRsp) Descriptor() ([]byte, []int) {
	return file_user_mgr_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserFlowRsp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserFlowRsp) GetFlow() []*GetUserFlowItemRsp {
	if x != nil {
		return x.Flow
	}
	return nil
}

func (x *GetUserFlowRsp) GetFlag() int32 {
	if x != nil {
		return x.Flag
	}
	return 0
}

func (x *GetUserFlowRsp) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetUserFlowItemRsp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FlowId         string                 `protobuf:"bytes,1,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount         int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	BizType        int32                  `protobuf:"varint,4,opt,name=biz_type,json=bizType,proto3" json:"biz_type,omitempty"`
	FlowType       int32                  `protobuf:"varint,5,opt,name=flow_type,json=flowType,proto3" json:"flow_type,omitempty"`
	CreateTime     string                 `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	CounterpartyId int64                  `protobuf:"varint,7,opt,name=counterparty_id,json=counterpartyId,proto3" json:"counterparty_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetUserFlowItemRsp) Reset() {
	*x = GetUserFlowItemRsp{}
	mi := &file_user_mgr_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserFlowItemRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserFlowItemRsp) ProtoMessage() {}

func (x *GetUserFlowItemRsp) ProtoReflect() protoreflect.Message {
	mi := &file_user_mgr_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserFlowItemRsp.ProtoReflect.Descriptor instead.
func (*GetUserFlowItemRsp) Descriptor() ([]byte, []int) {
	return file_user_mgr_proto_rawDescGZIP(), []int{14}
}

func (x *GetUserFlowItemRsp) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

func (x *GetUserFlowItemRsp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserFlowItemRsp) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *GetUserFlowItemRsp) GetBizType() int32 {
	if x != nil {
		return x.BizType
	}
	return 0
}

func (x *GetUserFlowItemRsp) GetFlowType() int32 {
	if x != nil {
		return x.FlowType
	}
	return 0
}

func (x *GetUserFlowItemRsp) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *GetUserFlowItemRsp) GetCounterpartyId() int64 {
	if x != nil {
		return x.CounterpartyId
	}
	return 0
}

var File_user_mgr_proto protoreflect.FileDescriptor

const file_user_mgr_proto_rawDesc = "" +
	"\n" +
	"\x0euser_mgr.proto\x12\buser_mgr\"\xf7\x01\n" +
	"\n" +
	"RegUserReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\x05R\x06gender\x12\x10\n" +
	"\x03age\x18\x04 \x01(\x05R\x03age\x12\x18\n" +
	"\aaddress\x18\x06 \x01(\tR\aaddress\x12\x14\n" +
	"\x05phone\x18\a \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\b \x01(\tR\x05email\x12\x17\n" +
	"\aid_type\x18\t \x01(\x05R\x06idType\x12\x17\n" +
	"\aid_card\x18\n" +
	" \x01(\tR\x06idCard\"B\n" +
	"\n" +
	"RegUserRsp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tis_repeat\x18\x02 \x01(\x05R\bisRepeat\")\n" +
	"\x0eGetUserInfoReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xdf\x01\n" +
	"\x0eGetUserInfoRsp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06gender\x18\x03 \x01(\x05R\x06gender\x12\x10\n" +
	"\x03age\x18\x04 \x01(\x05R\x03age\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\a \x01(\tR\x05email\x12\x17\n" +
	"\aid_type\x18\b \x01(\x05R\x06idType\x12\x17\n" +
	"\aid_card\x18\t \x01(\tR\x06idCard\",\n" +
	"\x11GetUserBalanceReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"F\n" +
	"\x11GetUserBalanceRsp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x03R\abalance\"\xe2\x01\n" +
	"\x11UpdateUserInfoReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06gender\x18\x03 \x01(\x05R\x06gender\x12\x10\n" +
	"\x03age\x18\x04 \x01(\x05R\x03age\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\a \x01(\tR\x05email\x12\x17\n" +
	"\aid_type\x18\b \x01(\x05R\x06idType\x12\x17\n" +
	"\aid_card\x18\t \x01(\tR\x06idCard\",\n" +
	"\x11UpdateUserInfoRsp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x97\x01\n" +
	"\n" +
	"DepositReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x1b\n" +
	"\tbank_type\x18\x03 \x01(\x03R\bbankType\x12\x1f\n" +
	"\vbind_serial\x18\x04 \x01(\tR\n" +
	"bindSerial\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\"?\n" +
	"\n" +
	"DepositRsp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x03R\abalance\"\x98\x01\n" +
	"\vWithdrawReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x1b\n" +
	"\tbank_type\x18\x03 \x01(\x03R\bbankType\x12\x1f\n" +
	"\vbind_serial\x18\x04 \x01(\tR\n" +
	"bindSerial\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\"@\n" +
	"\vWithdrawRsp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x03R\abalance\"W\n" +
	"\x0eGetUserFlowReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\x87\x01\n" +
	"\x0eGetUserFlowRsp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x120\n" +
	"\x04flow\x18\x02 \x03(\v2\x1c.user_mgr.GetUserFlowItemRspR\x04flow\x12\x12\n" +
	"\x04flag\x18\x03 \x01(\x05R\x04flag\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"\xe0\x01\n" +
	"\x12GetUserFlowItemRsp\x12\x17\n" +
	"\aflow_id\x18\x01 \x01(\tR\x06flowId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x19\n" +
	"\bbiz_type\x18\x04 \x01(\x05R\abizType\x12\x1b\n" +
	"\tflow_type\x18\x05 \x01(\x05R\bflowType\x12\x1f\n" +
	"\vcreate_time\x18\x06 \x01(\tR\n" +
	"createTime\x12'\n" +
	"\x0fcounterparty_id\x18\a \x01(\x03R\x0ecounterpartyId2\xcf\x01\n" +
	"\aUserMgr\x125\n" +
	"\aRegUser\x12\x14.user_mgr.RegUserReq\x1a\x14.user_mgr.RegUserRsp\x12J\n" +
	"\x0eUpdateUserInfo\x12\x1b.user_mgr.UpdateUserInfoReq\x1a\x1b.user_mgr.UpdateUserInfoRsp\x12A\n" +
	"\vGetUserInfo\x12\x18.user_mgr.GetUserInfoReq\x1a\x18.user_mgr.GetUserInfoRspB\x0fZ\r./user_mgr_pbb\x06proto3"

var (
	file_user_mgr_proto_rawDescOnce sync.Once
	file_user_mgr_proto_rawDescData []byte
)

func file_user_mgr_proto_rawDescGZIP() []byte {
	file_user_mgr_proto_rawDescOnce.Do(func() {
		file_user_mgr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_mgr_proto_rawDesc), len(file_user_mgr_proto_rawDesc)))
	})
	return file_user_mgr_proto_rawDescData
}

var file_user_mgr_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_user_mgr_proto_goTypes = []any{
	(*RegUserReq)(nil),         // 0: user_mgr.RegUserReq
	(*RegUserRsp)(nil),         // 1: user_mgr.RegUserRsp
	(*GetUserInfoReq)(nil),     // 2: user_mgr.GetUserInfoReq
	(*GetUserInfoRsp)(nil),     // 3: user_mgr.GetUserInfoRsp
	(*GetUserBalanceReq)(nil),  // 4: user_mgr.GetUserBalanceReq
	(*GetUserBalanceRsp)(nil),  // 5: user_mgr.GetUserBalanceRsp
	(*UpdateUserInfoReq)(nil),  // 6: user_mgr.UpdateUserInfoReq
	(*UpdateUserInfoRsp)(nil),  // 7: user_mgr.UpdateUserInfoRsp
	(*DepositReq)(nil),         // 8: user_mgr.DepositReq
	(*DepositRsp)(nil),         // 9: user_mgr.DepositRsp
	(*WithdrawReq)(nil),        // 10: user_mgr.WithdrawReq
	(*WithdrawRsp)(nil),        // 11: user_mgr.WithdrawRsp
	(*GetUserFlowReq)(nil),     // 12: user_mgr.GetUserFlowReq
	(*GetUserFlowRsp)(nil),     // 13: user_mgr.GetUserFlowRsp
	(*GetUserFlowItemRsp)(nil), // 14: user_mgr.GetUserFlowItemRsp
}
var file_user_mgr_proto_depIdxs = []int32{
	14, // 0: user_mgr.GetUserFlowRsp.flow:type_name -> user_mgr.GetUserFlowItemRsp
	0,  // 1: user_mgr.UserMgr.RegUser:input_type -> user_mgr.RegUserReq
	6,  // 2: user_mgr.UserMgr.UpdateUserInfo:input_type -> user_mgr.UpdateUserInfoReq
	2,  // 3: user_mgr.UserMgr.GetUserInfo:input_type -> user_mgr.GetUserInfoReq
	1,  // 4: user_mgr.UserMgr.RegUser:output_type -> user_mgr.RegUserRsp
	7,  // 5: user_mgr.UserMgr.UpdateUserInfo:output_type -> user_mgr.UpdateUserInfoRsp
	3,  // 6: user_mgr.UserMgr.GetUserInfo:output_type -> user_mgr.GetUserInfoRsp
	4,  // [4:7] is the sub-list for method output_type
	1,  // [1:4] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_user_mgr_proto_init() }
func file_user_mgr_proto_init() {
	if File_user_mgr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_mgr_proto_rawDesc), len(file_user_mgr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_mgr_proto_goTypes,
		DependencyIndexes: file_user_mgr_proto_depIdxs,
		MessageInfos:      file_user_mgr_proto_msgTypes,
	}.Build()
	File_user_mgr_proto = out.File
	file_user_mgr_proto_goTypes = nil
	file_user_mgr_proto_depIdxs = nil
}
