// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package mysql

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tRelationFieldNames          = builder.RawFieldNames(&TRelation{})
	tRelationRows                = strings.Join(tRelationFieldNames, ",")
	tRelationRowsExpectAutoSet   = strings.Join(stringx.Remove(tRelationFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tRelationRowsWithPlaceHolder = strings.Join(stringx.Remove(tRelationFieldNames, "`user_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	tRelationModel interface {
		Insert(ctx context.Context, data *TRelation) (sql.Result, error)
		FindOne(ctx context.Context, userId string) (*TRelation, error)
		Update(ctx context.Context, data *TRelation) error
		Delete(ctx context.Context, userId string) error
	}

	defaultTRelationModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TRelation struct {
		UserId     string    `db:"user_id"` // 用户ID
		Uid        int64     `db:"uid"`     // 主键
		State      int64     `db:"state"`   // 关联状态
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
	}
)

func newTRelationModel(conn sqlx.SqlConn) *defaultTRelationModel {
	return &defaultTRelationModel{
		conn:  conn,
		table: "`t_relation`",
	}
}

func (m *defaultTRelationModel) Delete(ctx context.Context, userId string) error {
	query := fmt.Sprintf("delete from %s where `user_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, userId)
	return err
}

func (m *defaultTRelationModel) FindOne(ctx context.Context, userId string) (*TRelation, error) {
	query := fmt.Sprintf("select %s from %s where `user_id` = ? limit 1", tRelationRows, m.table)
	var resp TRelation
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTRelationModel) Insert(ctx context.Context, data *TRelation) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, tRelationRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Uid, data.State)
	return ret, err
}

func (m *defaultTRelationModel) Update(ctx context.Context, data *TRelation) error {
	query := fmt.Sprintf("update %s set %s where `user_id` = ?", m.table, tRelationRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Uid, data.State, data.UserId)
	return err
}

func (m *defaultTRelationModel) tableName() string {
	return m.table
}
