// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package mysql

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tUidSegmentFieldNames          = builder.RawFieldNames(&TUidSegment{})
	tUidSegmentRows                = strings.Join(tUidSegmentFieldNames, ",")
	tUidSegmentRowsExpectAutoSet   = strings.Join(stringx.Remove(tUidSegmentFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tUidSegmentRowsWithPlaceHolder = strings.Join(stringx.Remove(tUidSegmentFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	tUidSegmentModel interface {
		Insert(ctx context.Context, data *TUidSegment) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TUidSegment, error)
		Update(ctx context.Context, data *TUidSegment) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTUidSegmentModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TUidSegment struct {
		Id         int64     `db:"id"`      // 主键
		UidMax     int64     `db:"uid_max"` // 已使用的最大用户ID
		Step       int64     `db:"step"`    // 步长
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
	}
)

func newTUidSegmentModel(conn sqlx.SqlConn) *defaultTUidSegmentModel {
	return &defaultTUidSegmentModel{
		conn:  conn,
		table: "`t_uid_segment`",
	}
}

func (m *defaultTUidSegmentModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTUidSegmentModel) FindOne(ctx context.Context, id int64) (*TUidSegment, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tUidSegmentRows, m.table)
	var resp TUidSegment
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTUidSegmentModel) Insert(ctx context.Context, data *TUidSegment) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, tUidSegmentRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.UidMax, data.Step)
	return ret, err
}

func (m *defaultTUidSegmentModel) Update(ctx context.Context, data *TUidSegment) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tUidSegmentRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UidMax, data.Step, data.Id)
	return err
}

func (m *defaultTUidSegmentModel) tableName() string {
	return m.table
}
