// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user_mgr.proto

package usermgr

import (
	"context"

	"user_mgr/user_mgr_pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DepositReq         = user_mgr_pb.DepositReq
	DepositRsp         = user_mgr_pb.DepositRsp
	GetUserBalanceReq  = user_mgr_pb.GetUserBalanceReq
	GetUserBalanceRsp  = user_mgr_pb.GetUserBalanceRsp
	GetUserFlowItemRsp = user_mgr_pb.GetUserFlowItemRsp
	GetUserFlowReq     = user_mgr_pb.GetUserFlowReq
	GetUserFlowRsp     = user_mgr_pb.GetUserFlowRsp
	GetUserInfoReq     = user_mgr_pb.GetUserInfoReq
	GetUserInfoRsp     = user_mgr_pb.GetUserInfoRsp
	RegUserReq         = user_mgr_pb.RegUserReq
	RegUserRsp         = user_mgr_pb.RegUserRsp
	UpdateUserInfoReq  = user_mgr_pb.UpdateUserInfoReq
	UpdateUserInfoRsp  = user_mgr_pb.UpdateUserInfoRsp
	WithdrawReq        = user_mgr_pb.WithdrawReq
	WithdrawRsp        = user_mgr_pb.WithdrawRsp

	UserMgr interface {
		RegUser(ctx context.Context, in *RegUserReq, opts ...grpc.CallOption) (*RegUserRsp, error)
		UpdateUserInfo(ctx context.Context, in *UpdateUserInfoReq, opts ...grpc.CallOption) (*UpdateUserInfoRsp, error)
		GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoRsp, error)
	}

	defaultUserMgr struct {
		cli zrpc.Client
	}
)

func NewUserMgr(cli zrpc.Client) UserMgr {
	return &defaultUserMgr{
		cli: cli,
	}
}

func (m *defaultUserMgr) RegUser(ctx context.Context, in *RegUserReq, opts ...grpc.CallOption) (*RegUserRsp, error) {
	client := user_mgr_pb.NewUserMgrClient(m.cli.Conn())
	return client.RegUser(ctx, in, opts...)
}

func (m *defaultUserMgr) UpdateUserInfo(ctx context.Context, in *UpdateUserInfoReq, opts ...grpc.CallOption) (*UpdateUserInfoRsp, error) {
	client := user_mgr_pb.NewUserMgrClient(m.cli.Conn())
	return client.UpdateUserInfo(ctx, in, opts...)
}

func (m *defaultUserMgr) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoRsp, error) {
	client := user_mgr_pb.NewUserMgrClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}
